site_name: HNSDNS documentation
site_description: HNSDNS setup, configuration and developer documentation.
site_author: Lumito
docs_dir: docs
repo_url: https://github.com/HNSDNS/docs
site_url: https://docs.hnsdns.com/

nav:
    - Home: index.md

theme:
  name: material

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://hnsdns.com
      name: HNSDNS's website
    - icon: fontawesome/brands/github
      link: https://github.com/HNSDNS
      name: HNSDNS on GitHub

copyright: Copyright &copy; 2022, <a href="https://www.lumito.net" target="_blank">Lumito</a>
