site_name: HNSDNS documentation
site_description: HNSDNS setup, configuration and developer documentation.
site_author: Lumito
docs_dir: docs
repo_url: https://github.com/HNSDNS/docs
repo_name: HNSDNS/docs
site_url: https://docs.hnsdns.com/
edit_uri: edit/main/docs/

nav:
  - Home: index.md
  - Getting started:
    - Introduction: getting-started/index.md
    - Windows:  getting-started/windows.md
  - Nameservers:
    - Introduction: nameservers/index.md
    - Creating an account: nameservers/creating-an-account.md
    - DNS management tutorial: nameservers/tutorial.md
  - Support: support/index.md

theme:
  name: material
  favicon: assets/hns-favicon_32x32.png
  features:
    - navigation.instant
    - navigation.tabs
    - navigation.top
    - toc.integrate
  icon:
    admonition:
      note: octicons/tag-16
  logo: assets/hns-white.png
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - search:
      lang: en
  - minify:
      minify_html: true

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/solid/globe
      link: https://hnsdns.com
      name: HNSDNS's website
    - icon: fontawesome/brands/github
      link: https://github.com/HNSDNS
      name: HNSDNS on GitHub

copyright: Copyright &copy; 2022, <a href="https://www.lumito.net" target="_blank">Lumito</a>. HNSDNS is not affiliated in any way with <a href="https://handshake.org" target="_blank">Handshake.org</a>.
